'use client';
import { useState } from 'react';
import { useLang } from '../../components/LangProvider';
const WUDU_EN=[{n:1,t:'Intention (Niyyah)',d:'Make intention in your heart to perform wudu for the sake of Allah.',a:'نِيَّة'},{n:2,t:'Say Bismillah',d:'Begin with Bismillah ir-Rahman ir-Raheem before starting.',a:'بِسْمِ اللَّهِ'},{n:3,t:'Wash Hands',d:'Wash both hands up to the wrists three times, right first.',a:'غَسْل اليَدَين'},{n:4,t:'Rinse Mouth',d:'Take water into your mouth and rinse it three times.',a:'المَضْمَضَة'},{n:5,t:'Rinse Nose',d:'Sniff water into nostrils and blow out three times.',a:'الاسْتِنْشَاق'},{n:6,t:'Wash Face',d:'Wash entire face from forehead to chin, ear to ear, three times.',a:'غَسْل الوَجْه'},{n:7,t:'Wash Arms',d:'Wash both arms up to elbows three times, right first.',a:'غَسْل الذِّرَاعَين'},{n:8,t:'Wipe Head',d:'Pass wet hands over head from front to back once.',a:'مَسْح الرَّأْس'},{n:9,t:'Wipe Ears',d:'Wipe inside and outside of both ears with wet fingers once.',a:'مَسْح الأُذُنَين'},{n:10,t:'Wash Feet',d:'Wash both feet up to ankles three times, right foot first.',a:'غَسْل القَدَمَين'}];
const WUDU_BN=[{n:1,t:'নিয়্যত',d:'আল্লাহর জন্য ওযু করার নিয়্যত মনে মনে করুন।',a:'نِيَّة'},{n:2,t:'বিসমিল্লাহ বলুন',d:'শুরু করার আগে বিসমিল্লাহির রাহমানির রাহিম বলুন।',a:'بِسْمِ اللَّهِ'},{n:3,t:'হাত ধোয়া',d:'উভয় হাত কব্জি পর্যন্ত তিনবার ধোয়া, ডান হাত আগে।',a:'غَسْل اليَدَين'},{n:4,t:'কুলি করা',d:'মুখে পানি নিয়ে তিনবার ভালোভাবে কুলি করুন।',a:'المَضْمَضَة'},{n:5,t:'নাকে পানি দেওয়া',d:'নাকে পানি দিয়ে তিনবার পরিষ্কার করুন।',a:'الاسْتِنْشَاق'},{n:6,t:'মুখ ধোয়া',d:'কপাল থেকে থুতনি পর্যন্ত সম্পূর্ণ মুখ তিনবার ধোয়া।',a:'غَسْل الوَجْه'},{n:7,t:'হাত ধোয়া (কনুই পর্যন্ত)',d:'উভয় হাত কনুই পর্যন্ত তিনবার ধোয়া, ডান হাত আগে।',a:'غَسْل الذِّرَاعَين'},{n:8,t:'মাথা মাসেহ করা',d:'ভেজা হাত দিয়ে সামনে থেকে পেছনে মাথা একবার মাসেহ করুন।',a:'مَسْح الرَّأْس'},{n:9,t:'কান মাসেহ করা',d:'ভেজা আঙুল দিয়ে উভয় কানের ভেতরে ও বাইরে একবার মাসেহ করুন।',a:'مَسْح الأُذُنَين'},{n:10,t:'পা ধোয়া',d:'উভয় পা গোড়ালি পর্যন্ত তিনবার ধোয়া, ডান পা আগে।',a:'غَسْل القَدَمَين'}];
const PRAYERS_EN=[{name:'Fajr',bnName:'ফজর',arabic:'الفجر',emoji:'🌙',rakaat:2,time:'Before sunrise',bnTime:'সূর্যোদয়ের আগে',steps:[{t:'Takbeer',d:'Stand facing Qibla. Raise hands to ears saying Allahu Akbar.',a:'اللَّهُ أَكْبَر'},{t:'Surah Al-Fatihah',d:'Recite the opening chapter of the Quran in every rakah.',a:'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ'},{t:'Additional Surah',d:'Recite any surah after Al-Fatihah.',a:'قُلْ هُوَ اللَّهُ أَحَدٌ'},{t:'Ruku (Bowing)',d:'Bow with hands on knees. Say SubhanAllah al-Azeem 3 times.',a:'سُبْحَانَ رَبِّيَ الْعَظِيمِ'},{t:'Rising from Ruku',d:'Stand and say Sami Allahu liman hamidah.',a:'سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ'},{t:'Sajdah (Prostration)',d:'Prostrate on 7 bones. Say SubhanAllah al-Ala 3 times.',a:'سُبْحَانَ رَبِّيَ الْأَعْلَى'},{t:'Sitting Between Sajdah',d:'Sit and say Rabbighfirli twice.',a:'رَبِّ اغْفِرْ لِي'},{t:'Tashahhud',d:'After final rakah sit and recite At-Tahiyyat.',a:'التَّحِيَّاتُ لِلَّهِ'},{t:'Salaam',d:'Turn right then left saying Assalamu Alaikum wa Rahmatullah.',a:'السَّلَامُ عَلَيْكُمْ'}]},{name:'Dhuhr',bnName:'যোহর',arabic:'الظهر',emoji:'☀️',rakaat:4,time:'Midday',bnTime:'দুপুরে',steps:[{t:'4 Rakaat',d:'First 2 rakaat with Fatihah + additional surah like Fajr.',a:''},{t:'Middle Tashahhud',d:'After 2nd rakah sit for short Tashahhud then stand for 3rd.',a:'التَّحِيَّاتُ'},{t:'3rd & 4th Rakaat',d:'Recite only Al-Fatihah in last two rakaat.',a:'الْفَاتِحَة فَقَط'},{t:'Final Tashahhud & Salaam',d:'Complete Tashahhud with Durood Ibrahim then salaam.',a:'السَّلَام'}]},{name:'Asr',bnName:'আসর',arabic:'العصر',emoji:'🌤️',rakaat:4,time:'Afternoon',bnTime:'বিকেলে',steps:[{t:'Same as Dhuhr',d:'4 rakaat performed identically to Dhuhr prayer.',a:''},{t:'Timing',d:'Asr begins when shadow equals twice the object height.',a:'وَقْتُ العَصْر'}]},{name:'Maghrib',bnName:'মাগরিব',arabic:'المغرب',emoji:'🌇',rakaat:3,time:'After sunset',bnTime:'সূর্যাস্তের পর',steps:[{t:'First Two Rakaat',d:'Same as Fajr with Fatihah and additional surah.',a:''},{t:'Third Rakaat',d:'Stand and recite only Al-Fatihah, then ruku and sajdah.',a:'الفَاتِحَة فَقَط'},{t:'Final Salaam',d:'Sit, complete Tashahhud with Durood Ibrahim, then salaam.',a:'السَّلَام'}]},{name:'Isha',bnName:'ইশা',arabic:'العشاء',emoji:'🌃',rakaat:4,time:'Night',bnTime:'রাতে',steps:[{t:'Same as Dhuhr',d:'4 rakaat, identical structure to Dhuhr.',a:''},{t:'Witr (Sunnah)',d:'After Isha, pray 3 rakaat Witr — the beloved odd prayer.',a:'صَلَاة الوِتْر'}]}];
export default function LearnPage(){
  const{t,lang}=useLang();const[tab,setTab]=useState('wudu');const[sel,setSel]=useState(null);const[exp,setExp]=useState(null);
  const WUDU=lang==='bn'?WUDU_BN:WUDU_EN;
  return(<div style={{maxWidth:500,margin:'0 auto',padding:'0 16px'}}>
    <div style={{paddingTop:56,paddingBottom:16}}><h1 className="text-gold" style={{fontSize:28,fontWeight:800}}>{t('learn.title')}</h1><p style={{color:'#6a7a8a',fontSize:14,marginTop:4}}>{t('learn.subtitle')}</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>
      {['wudu','prayers'].map(tk=>(<button key={tk} onClick={()=>{setTab(tk);setSel(null)}} style={{flex:1,padding:'10px',borderRadius:12,border:'1px solid',cursor:'pointer',fontWeight:600,fontSize:13,transition:'all 0.2s',background:tab===tk?'linear-gradient(135deg,#1a6b4a,#0a3622)':'rgba(255,255,255,0.04)',color:tab===tk?'#f0d060':'#6a7a8a',borderColor:tab===tk?'rgba(201,162,39,0.4)':'rgba(255,255,255,0.08)'}}>{t('learn.tab.'+tk)}</button>))}
    </div>
    {tab==='wudu'&&(<div>
      <div className="card-gold" style={{padding:'14px 16px',marginBottom:16,textAlign:'center'}}><div style={{fontFamily:'Amiri,serif',fontSize:18,color:'#f0d060',marginBottom:4}}>الوُضُوء</div><div style={{fontSize:13,color:'#8a9aaa'}}>{t('learn.wudu.sub')}</div></div>
      {WUDU.map(({n,t:title,d,a})=>(<div key={n} className="card" style={{marginBottom:10,padding:'14px 16px',display:'flex',gap:14,alignItems:'flex-start'}}><div style={{width:32,height:32,borderRadius:'50%',background:'linear-gradient(135deg,#c9a227,#a07d1a)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:13,fontWeight:800,color:'#040d1a',flexShrink:0}}>{n}</div><div style={{flex:1}}><div style={{fontWeight:700,color:'#fff',fontSize:14,marginBottom:2}}>{title}</div><div style={{fontSize:12,color:'#6a7a8a',lineHeight:1.5}}>{d}</div>{a&&<div style={{fontFamily:'Amiri,serif',fontSize:16,color:'#c9a227',marginTop:6,textAlign:'right'}}>{a}</div>}</div></div>))}
    </div>)}
    {tab==='prayers'&&!sel&&(<div>
      <div style={{fontSize:13,color:'#6a7a8a',marginBottom:12}}>{t('learn.select')}</div>
      {PRAYERS_EN.map(p=>(<div key={p.name} className="card" onClick={()=>setSel(p)} style={{marginBottom:12,padding:'16px',cursor:'pointer',display:'flex',alignItems:'center',gap:14}}><div style={{fontSize:32}}>{p.emoji}</div><div style={{flex:1}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontWeight:700,color:'#fff',fontSize:16}}>{lang==='bn'?p.bnName:p.name}</span><span style={{fontFamily:'Amiri,serif',fontSize:18,color:'#c9a227'}}>{p.arabic}</span></div><div style={{fontSize:12,color:'#6a7a8a',marginTop:2}}>{p.rakaat} {t('learn.rakaat')} · {lang==='bn'?p.bnTime:p.time}</div></div><div style={{color:'#c9a227',fontSize:18}}>›</div></div>))}
    </div>)}
    {tab==='prayers'&&sel&&(<div>
      <button onClick={()=>setSel(null)} style={{background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.1)',color:'#aaa',borderRadius:10,padding:'8px 14px',cursor:'pointer',marginBottom:16,fontSize:13}}>{t('learn.back')}</button>
      <div className="card-gold" style={{padding:'16px',marginBottom:16,textAlign:'center'}}><div style={{fontSize:36}}>{sel.emoji}</div><div style={{fontSize:22,fontWeight:800,color:'#fff',marginTop:4}}>{lang==='bn'?sel.bnName:sel.name}</div><div style={{fontFamily:'Amiri,serif',fontSize:20,color:'#c9a227'}}>{sel.arabic}</div><div style={{fontSize:13,color:'#8a9aaa'}}>{sel.rakaat} {t('learn.rakaat')} · {lang==='bn'?sel.bnTime:sel.time}</div></div>
      {sel.steps.map((s,i)=>(<div key={i} className="card" style={{marginBottom:10,padding:'14px 16px',cursor:'pointer'}} onClick={()=>setExp(exp===i?null:i)}><div style={{display:'flex',alignItems:'center',gap:12}}><div style={{width:28,height:28,borderRadius:'50%',background:'rgba(201,162,39,0.15)',border:'1px solid rgba(201,162,39,0.3)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:12,fontWeight:700,color:'#c9a227',flexShrink:0}}>{i+1}</div><div style={{flex:1,fontWeight:600,color:'#ddd',fontSize:14}}>{s.t}</div><div style={{color:'#c9a227',transition:'transform 0.2s',transform:exp===i?'rotate(90deg)':'none'}}>›</div></div>{exp===i&&(<div style={{marginTop:10,paddingLeft:40}}><div style={{fontSize:13,color:'#8a9aaa',lineHeight:1.6}}>{s.d}</div>{s.a&&<div style={{fontFamily:'Amiri,serif',fontSize:18,color:'#c9a227',marginTop:8,textAlign:'right',lineHeight:1.8}}>{s.a}</div>}</div>)}</div>))}
    </div>)}
    <div style={{height:20}}/>
  </div>);
}