'use client';
import { useState } from 'react';
const WUDU=[{n:1,t:'Intention (Niyyah)',d:'Make intention in your heart to perform wudu for the sake of Allah.',a:'نِيَّة'},{n:2,t:'Say Bismillah',d:'Begin with Bismillah ir-Rahman ir-Raheem before starting.',a:'بِسْمِ اللَّهِ'},{n:3,t:'Wash Hands',d:'Wash both hands up to the wrists three times, right first.',a:'غَسْل اليَدَين'},{n:4,t:'Rinse Mouth',d:'Take water into your mouth and rinse it three times.',a:'المَضْمَضَة'},{n:5,t:'Rinse Nose',d:'Sniff water into nostrils and blow out three times.',a:'الاسْتِنْشَاق'},{n:6,t:'Wash Face',d:'Wash entire face from forehead to chin, ear to ear, three times.',a:'غَسْل الوَجْه'},{n:7,t:'Wash Arms',d:'Wash both arms up to elbows three times, right first.',a:'غَسْل الذِّرَاعَين'},{n:8,t:'Wipe Head',d:'Pass wet hands over head from front to back once.',a:'مَسْح الرَّأْس'},{n:9,t:'Wipe Ears',d:'Wipe inside and outside of both ears with wet fingers once.',a:'مَسْح الأُذُنَين'},{n:10,t:'Wash Feet',d:'Wash both feet up to ankles three times, right foot first.',a:'غَسْل القَدَمَين'}];
const PRAYERS=[{name:'Fajr',arabic:'الفجر',emoji:'🌙',rakaat:2,time:'Before sunrise',steps:[{t:'Takbeer',d:'Stand facing Qibla. Raise hands to ears saying Allahu Akbar.',a:'اللَّهُ أَكْبَر'},{t:'Surah Al-Fatihah',d:'Recite the opening chapter of the Quran in every rakah.',a:'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ'},{t:'Additional Surah',d:'Recite any surah from the Quran after Al-Fatihah.',a:'قُلْ هُوَ اللَّهُ أَحَدٌ'},{t:'Ruku (Bowing)',d:'Bow with hands on knees. Say SubhanAllah al-Azeem 3 times.',a:'سُبْحَانَ رَبِّيَ الْعَظِيمِ'},{t:'Rising from Ruku',d:'Stand and say Sami Allahu liman hamidah, Rabbana lakal hamd.',a:'سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ'},{t:'Sajdah (Prostration)',d:'Prostrate on 7 bones. Say SubhanAllah al-Ala 3 times.',a:'سُبْحَانَ رَبِّيَ الْأَعْلَى'},{t:'Sitting Between Sajdah',d:'Sit and say Rabbighfirli twice.',a:'رَبِّ اغْفِرْ لِي'},{t:'Tashahhud',d:'After final rakah, sit and recite At-Tahiyyat.',a:'التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ'},{t:'Salaam',d:'Turn right then left saying Assalamu Alaikum wa Rahmatullah.',a:'السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ'}]},{name:'Dhuhr',arabic:'الظهر',emoji:'☀️',rakaat:4,time:'Midday',steps:[{t:'4 Rakaat — Same as Fajr for 2',d:'Perform first two rakaat like Fajr with Fatihah and additional surah.',a:''},{t:'Middle Tashahhud',d:'After 2nd rakah, sit for short Tashahhud then stand for 3rd.',a:'التَّحِيَّاتُ'},{t:'3rd & 4th Rakaat',d:'Recite only Al-Fatihah (no additional surah in last two rakaat).',a:'الْفَاتِحَة فَقَط'},{t:'Final Tashahhud & Salaam',d:'Complete full Tashahhud with Durood Ibrahim then salaam.',a:'السَّلَام'}]},{name:'Asr',arabic:'العصر',emoji:'🌤️',rakaat:4,time:'Afternoon',steps:[{t:'Same structure as Dhuhr',d:'4 rakaat performed identically to Dhuhr prayer.',a:''},{t:'Key timing',d:'Asr begins when shadow equals twice the object height.',a:'وَقْتُ العَصْر'}]},{name:'Maghrib',arabic:'المغرب',emoji:'🌇',rakaat:3,time:'After sunset',steps:[{t:'First Two Rakaat',d:'Same as Fajr with Fatihah and additional surah, Tashahhud after 2nd.',a:''},{t:'Third Rakaat',d:'Stand and recite only Al-Fatihah, then complete ruku and sajdah.',a:'الفَاتِحَة فَقَط'},{t:'Final Salaam',d:'Sit, complete Tashahhud with Durood Ibrahim, then salaam.',a:'السَّلَام'}]},{name:'Isha',arabic:'العشاء',emoji:'🌃',rakaat:4,time:'Night',steps:[{t:'Same as Dhuhr',d:'4 rakaat, identical structure to Dhuhr prayer.',a:''},{t:'Witr Prayer (Sunnah)',d:'After Isha, pray 3 rakaat Witr — the beloved odd-numbered prayer.',a:'صَلَاة الوِتْر'}]}];
export default function LearnPage(){
  const[tab,setTab]=useState('wudu');const[sel,setSel]=useState(null);const[exp,setExp]=useState(null);
  return(<div style={{maxWidth:500,margin:'0 auto',padding:'0 16px'}}>
    <div style={{paddingTop:56,paddingBottom:16}}><h1 className="text-gold" style={{fontSize:28,fontWeight:800}}>Learn to Pray</h1><p style={{color:'#6a7a8a',fontSize:14,marginTop:4}}>Step-by-step guide to perfect your Salah</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>
      {['wudu','prayers'].map(t=>(<button key={t} onClick={()=>{setTab(t);setSel(null)}} style={{flex:1,padding:'10px',borderRadius:12,border:'1px solid',cursor:'pointer',fontWeight:600,fontSize:13,transition:'all 0.2s',background:tab===t?'linear-gradient(135deg,#1a6b4a,#0a3622)':'rgba(255,255,255,0.04)',color:tab===t?'#f0d060':'#6a7a8a',borderColor:tab===t?'rgba(201,162,39,0.4)':'rgba(255,255,255,0.08)'}}>{t==='wudu'?'💧 Wudu':'🕌 Prayers'}</button>))}
    </div>
    {tab==='wudu'&&(<div>
      <div className="card-gold" style={{padding:'14px 16px',marginBottom:16,textAlign:'center'}}><div style={{fontFamily:'Amiri,serif',fontSize:18,color:'#f0d060',marginBottom:4}}>الوُضُوء</div><div style={{fontSize:13,color:'#8a9aaa'}}>Purification before prayer</div></div>
      {WUDU.map(({n,t,d,a})=>(<div key={n} className="card" style={{marginBottom:10,padding:'14px 16px',display:'flex',gap:14,alignItems:'flex-start'}}><div style={{width:32,height:32,borderRadius:'50%',background:'linear-gradient(135deg,#c9a227,#a07d1a)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:13,fontWeight:800,color:'#040d1a',flexShrink:0}}>{n}</div><div style={{flex:1}}><div style={{fontWeight:700,color:'#fff',fontSize:14,marginBottom:2}}>{t}</div><div style={{fontSize:12,color:'#6a7a8a',lineHeight:1.5}}>{d}</div>{a&&<div style={{fontFamily:'Amiri,serif',fontSize:16,color:'#c9a227',marginTop:6,textAlign:'right'}}>{a}</div>}</div></div>))}
    </div>)}
    {tab==='prayers'&&!sel&&(<div>
      <div style={{fontSize:12,color:'#6a7a8a',marginBottom:12}}>Select a prayer to learn its steps:</div>
      {PRAYERS.map(p=>(<div key={p.name} className="card" onClick={()=>setSel(p)} style={{marginBottom:12,padding:'16px',cursor:'pointer',display:'flex',alignItems:'center',gap:14}}><div style={{fontSize:32}}>{p.emoji}</div><div style={{flex:1}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontWeight:700,color:'#fff',fontSize:16}}>{p.name}</span><span style={{fontFamily:'Amiri,serif',fontSize:18,color:'#c9a227'}}>{p.arabic}</span></div><div style={{fontSize:12,color:'#6a7a8a',marginTop:2}}>{p.rakaat} Rakaat · {p.time}</div></div><div style={{color:'#c9a227',fontSize:18}}>›</div></div>))}
    </div>)}
    {tab==='prayers'&&sel&&(<div>
      <button onClick={()=>setSel(null)} style={{background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.1)',color:'#aaa',borderRadius:10,padding:'8px 14px',cursor:'pointer',marginBottom:16,fontSize:13}}>← Back</button>
      <div className="card-gold" style={{padding:'16px',marginBottom:16,textAlign:'center'}}><div style={{fontSize:36}}>{sel.emoji}</div><div style={{fontSize:22,fontWeight:800,color:'#fff',marginTop:4}}>{sel.name} Prayer</div><div style={{fontFamily:'Amiri,serif',fontSize:20,color:'#c9a227'}}>{sel.arabic}</div><div style={{fontSize:13,color:'#8a9aaa',marginTop:4}}>{sel.rakaat} Rakaat · {sel.time}</div></div>
      {sel.steps.map((s,i)=>(<div key={i} className="card" style={{marginBottom:10,padding:'14px 16px',cursor:'pointer'}} onClick={()=>setExp(exp===i?null:i)}><div style={{display:'flex',alignItems:'center',gap:12}}><div style={{width:28,height:28,borderRadius:'50%',background:'rgba(201,162,39,0.15)',border:'1px solid rgba(201,162,39,0.3)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:12,fontWeight:700,color:'#c9a227',flexShrink:0}}>{i+1}</div><div style={{flex:1,fontWeight:600,color:'#ddd',fontSize:14}}>{s.t}</div><div style={{color:'#c9a227',transition:'transform 0.2s',transform:exp===i?'rotate(90deg)':'none'}}>›</div></div>{exp===i&&(<div style={{marginTop:10,paddingLeft:40}}><div style={{fontSize:13,color:'#8a9aaa',lineHeight:1.6}}>{s.d}</div>{s.a&&<div style={{fontFamily:'Amiri,serif',fontSize:18,color:'#c9a227',marginTop:8,textAlign:'right',lineHeight:1.8}}>{s.a}</div>}</div>)}</div>))}
    </div>)}
    <div style={{height:20}}/>
  </div>);
}