'use client';
import { useState, useEffect } from 'react';
const SURAHS=[{n:1,name:'Al-Fatihah',arabic:'الفاتحة',meaning:'The Opening',v:7},{n:2,name:'Al-Baqarah',arabic:'البقرة',meaning:'The Cow',v:286},{n:3,name:'Ali Imran',arabic:'آل عمران',meaning:'Family of Imran',v:200},{n:4,name:'An-Nisa',arabic:'النساء',meaning:'The Women',v:176},{n:5,name:'Al-Maidah',arabic:'المائدة',meaning:'The Table Spread',v:120},{n:6,name:'Al-Anam',arabic:'الأنعام',meaning:'The Cattle',v:165},{n:9,name:'At-Tawbah',arabic:'التوبة',meaning:'The Repentance',v:129},{n:18,name:'Al-Kahf',arabic:'الكهف',meaning:'The Cave',v:110},{n:36,name:'Ya-Sin',arabic:'يس',meaning:'Ya Sin',v:83},{n:55,name:'Ar-Rahman',arabic:'الرحمن',meaning:'The Beneficent',v:78},{n:56,name:'Al-Waqiah',arabic:'الواقعة',meaning:'The Inevitable',v:96},{n:67,name:'Al-Mulk',arabic:'الملك',meaning:'The Sovereignty',v:30},{n:78,name:'An-Naba',arabic:'النبأ',meaning:'The Tidings',v:40},{n:112,name:'Al-Ikhlas',arabic:'الإخلاص',meaning:'The Sincerity',v:4},{n:113,name:'Al-Falaq',arabic:'الفلق',meaning:'The Daybreak',v:5},{n:114,name:'An-Nas',arabic:'الناس',meaning:'Mankind',v:6}];
export default function QuranPage(){
  const[sel,setSel]=useState(null);const[ayahs,setAyahs]=useState([]);const[loading,setLoading]=useState(false);const[bk,setBk]=useState([]);const[search,setSearch]=useState('');const[showBk,setShowBk]=useState(false);const[err,setErr]=useState(null);
  useEffect(()=>{setBk(JSON.parse(localStorage.getItem('np_bookmarks')||'[]'))},[]);
  async function load(s){setSel(s);setLoading(true);setErr(null);setAyahs([]);try{const[ar,en]=await Promise.all([fetch('https://api.alquran.cloud/v1/surah/'+s.n),fetch('https://api.alquran.cloud/v1/surah/'+s.n+'/en.asad')]);const[ad,ed]=await Promise.all([ar.json(),en.json()]);const aa=ad.data?.ayahs||[];const ea=ed.data?.ayahs||[];setAyahs(aa.map((a,i)=>({...a,tr:ea[i]?.text||''})))}catch{setErr('Failed to load — check your connection')}setLoading(false)}
  function toggleBk(a){const k=sel.n+':'+a.numberInSurah;const ex=bk.find(b=>b.key===k);const u=ex?bk.filter(b=>b.key!==k):[...bk,{key:k,surah:sel.name,ayah:a.numberInSurah,arabic:a.text,tr:a.tr}];setBk(u);localStorage.setItem('np_bookmarks',JSON.stringify(u))}
  const filtered=SURAHS.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())||s.arabic.includes(search)||s.meaning.toLowerCase().includes(search.toLowerCase()));
  return(<div style={{maxWidth:500,margin:'0 auto',padding:'0 16px'}}>
    <div style={{paddingTop:56,paddingBottom:16}}><h1 className="text-gold" style={{fontSize:28,fontWeight:800}}>Qur'an</h1><p style={{color:'#6a7a8a',fontSize:14,marginTop:4}}>Arabic text with English translation</p></div>
    {!sel&&!showBk&&(<div>
      <div style={{display:'flex',gap:8,marginBottom:16}}>
        <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search surah..." style={{flex:1,background:'rgba(255,255,255,0.05)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:12,padding:'10px 14px',color:'#fff',fontSize:14,outline:'none'}}/>
        <button onClick={()=>setShowBk(true)} style={{background:'rgba(201,162,39,0.12)',border:'1px solid rgba(201,162,39,0.25)',borderRadius:12,padding:'10px 14px',cursor:'pointer',fontSize:16}}>🔖</button>
      </div>
      <div className="card-gold" style={{padding:'12px 16px',marginBottom:16,textAlign:'center'}}><div style={{fontFamily:'Amiri,serif',fontSize:16,color:'#f0d060'}}>بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ</div></div>
      {filtered.map(s=>(<div key={s.n} className="card" onClick={()=>load(s)} style={{marginBottom:8,padding:'14px 16px',cursor:'pointer',display:'flex',alignItems:'center',gap:12}}><div style={{width:36,height:36,borderRadius:10,background:'rgba(201,162,39,0.12)',border:'1px solid rgba(201,162,39,0.2)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:12,fontWeight:800,color:'#c9a227',flexShrink:0}}>{s.n}</div><div style={{flex:1}}><div style={{fontWeight:700,color:'#fff',fontSize:14}}>{s.name}</div><div style={{fontSize:11,color:'#5a6a7a',marginTop:1}}>{s.meaning} · {s.v} verses</div></div><div style={{fontFamily:'Amiri,serif',fontSize:18,color:'#c9a227'}}>{s.arabic}</div></div>))}
      <div style={{textAlign:'center',padding:16,fontSize:12,color:'#4a5a6a'}}>Tap any surah to start reading</div>
    </div>)}
    {showBk&&(<div>
      <button onClick={()=>setShowBk(false)} style={{background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.1)',color:'#aaa',borderRadius:10,padding:'8px 14px',cursor:'pointer',marginBottom:16,fontSize:13}}>← Back</button>
      <div style={{fontSize:14,fontWeight:700,color:'#c9a227',marginBottom:12}}>🔖 Bookmarks ({bk.length})</div>
      {bk.length===0?(<div className="card" style={{padding:'30px',textAlign:'center',color:'#5a6a7a',fontSize:13}}>No bookmarks yet</div>):bk.map(b=>(<div key={b.key} className="ayah-card" style={{marginBottom:10}}><div style={{fontSize:11,color:'#c9a227',fontWeight:600,marginBottom:6}}>{b.surah} · Ayah {b.ayah}</div><div style={{fontFamily:'Amiri,serif',fontSize:20,color:'#f0d060',textAlign:'right',lineHeight:1.8}}>{b.arabic}</div><div style={{fontSize:12,color:'#7a8a9a',marginTop:8,lineHeight:1.6}}>{b.tr}</div></div>))}
    </div>)}
    {sel&&(<div>
      <button onClick={()=>{setSel(null);setAyahs([])}} style={{background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.1)',color:'#aaa',borderRadius:10,padding:'8px 14px',cursor:'pointer',marginBottom:16,fontSize:13}}>← Surahs</button>
      <div className="card-gold" style={{padding:'16px',marginBottom:16,textAlign:'center'}}><div style={{fontFamily:'Amiri,serif',fontSize:26,color:'#f0d060'}}>{sel.arabic}</div><div style={{fontSize:16,fontWeight:700,color:'#fff',marginTop:4}}>{sel.name}</div><div style={{fontSize:12,color:'#8a9aaa'}}>{sel.meaning} · {sel.v} Verses</div>{sel.n!==9&&<div style={{fontFamily:'Amiri,serif',fontSize:14,color:'#c9a227',marginTop:8}}>بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ</div>}</div>
      {loading&&Array(4).fill(0).map((_,i)=>(<div key={i} className="ayah-card" style={{marginBottom:10}}><div className="skeleton" style={{height:60,marginBottom:8}}/><div className="skeleton" style={{height:16,width:'80%'}}/></div>))}
      {err&&<div style={{color:'#e07070',textAlign:'center',padding:20,fontSize:13}}>{err}</div>}
      {ayahs.map(a=>{const k=sel.n+':'+a.numberInSurah;const bked=bk.find(b=>b.key===k);return(<div key={a.numberInSurah} className="ayah-card" style={{marginBottom:10}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:10}}><div style={{width:30,height:30,borderRadius:'50%',background:'linear-gradient(135deg,#c9a227,#a07d1a)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:11,fontWeight:800,color:'#040d1a'}}>{a.numberInSurah}</div><button onClick={()=>toggleBk(a)} style={{background:'none',border:'none',cursor:'pointer',fontSize:16,opacity:bked?1:0.4}}>🔖</button></div><div style={{fontFamily:'Amiri,serif',fontSize:22,color:'#f0d060',textAlign:'right',lineHeight:2,marginBottom:12}}>{a.text}</div><div style={{fontSize:13,color:'#7a8a9a',lineHeight:1.7,borderTop:'1px solid rgba(255,255,255,0.05)',paddingTop:10}}>{a.tr}</div></div>);})}
    </div>)}
    <div style={{height:20}}/>
  </div>);
}