'use client';
import { useState, useEffect } from 'react';
import { useLang } from '../../components/LangProvider';
const SURAHS=[{n:1,name:'Al-Fatihah',bnName:'আল-ফাতিহা',arabic:'الفاتحة',meaning:'The Opening',bnMeaning:'সূচনা',v:7},{n:2,name:'Al-Baqarah',bnName:'আল-বাকারা',arabic:'البقرة',meaning:'The Cow',bnMeaning:'গাভী',v:286},{n:3,name:'Ali Imran',bnName:'আলে ইমরান',arabic:'آل عمران',meaning:'Family of Imran',bnMeaning:'ইমরানের পরিবার',v:200},{n:18,name:'Al-Kahf',bnName:'আল-কাহফ',arabic:'الكهف',meaning:'The Cave',bnMeaning:'গুহা',v:110},{n:36,name:'Ya-Sin',bnName:'ইয়াসিন',arabic:'يس',meaning:'Ya Sin',bnMeaning:'ইয়া সিন',v:83},{n:55,name:'Ar-Rahman',bnName:'আর-রাহমান',arabic:'الرحمن',meaning:'The Beneficent',bnMeaning:'পরম করুণাময়',v:78},{n:67,name:'Al-Mulk',bnName:'আল-মুলক',arabic:'الملك',meaning:'The Sovereignty',bnMeaning:'রাজত্ব',v:30},{n:112,name:'Al-Ikhlas',bnName:'আল-ইখলাস',arabic:'الإخلاص',meaning:'The Sincerity',bnMeaning:'একনিষ্ঠতা',v:4},{n:113,name:'Al-Falaq',bnName:'আল-ফালাক',arabic:'الفلق',meaning:'The Daybreak',bnMeaning:'ভোরের আলো',v:5},{n:114,name:'An-Nas',bnName:'আন-নাস',arabic:'الناس',meaning:'Mankind',bnMeaning:'মানবজাতি',v:6}];
export default function QuranPage(){
  const{t,lang}=useLang();const[sel,setSel]=useState(null);const[ayahs,setAyahs]=useState([]);const[loading,setLoading]=useState(false);const[bk,setBk]=useState([]);const[search,setSearch]=useState('');const[showBk,setShowBk]=useState(false);const[err,setErr]=useState(null);
  useEffect(()=>{setBk(JSON.parse(localStorage.getItem('np_bookmarks')||'[]'))},[]);
  async function loadSurah(s){setSel(s);setLoading(true);setErr(null);setAyahs([]);try{const[ar,en]=await Promise.all([fetch('https://api.alquran.cloud/v1/surah/'+s.n),fetch('https://api.alquran.cloud/v1/surah/'+s.n+'/en.asad')]);const[ad,ed]=await Promise.all([ar.json(),en.json()]);const aa=ad.data?.ayahs||[];const ea=ed.data?.ayahs||[];setAyahs(aa.map((a,i)=>({...a,tr:ea[i]?.text||''})))}catch{setErr('Failed to load — check your connection')}setLoading(false)}
  function toggleBk(a){const k=sel.n+':'+a.numberInSurah;const ex=bk.find(b=>b.key===k);const u=ex?bk.filter(b=>b.key!==k):[...bk,{key:k,surah:sel.name,ayah:a.numberInSurah,arabic:a.text,tr:a.tr}];setBk(u);localStorage.setItem('np_bookmarks',JSON.stringify(u))}
  const filtered=SURAHS.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())||s.bnName.includes(search)||s.arabic.includes(search));
  return(<div style={{maxWidth:500,margin:'0 auto',padding:'0 16px'}}>
    <div style={{paddingTop:56,paddingBottom:16}}><h1 className="text-gold" style={{fontSize:28,fontWeight:800}}>{t('quran.title')}</h1><p style={{color:'#6a7a8a',fontSize:14,marginTop:4}}>{t('quran.subtitle')}</p></div>
    {!sel&&!showBk&&(<div>
      <div style={{display:'flex',gap:8,marginBottom:16}}>
        <input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('quran.search')} style={{flex:1,background:'rgba(255,255,255,0.05)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:12,padding:'10px 14px',color:'#fff',fontSize:14,outline:'none'}}/>
        <button onClick={()=>setShowBk(true)} style={{background:'rgba(201,162,39,0.12)',border:'1px solid rgba(201,162,39,0.25)',borderRadius:12,padding:'10px 14px',cursor:'pointer',fontSize:16}}>🔖</button>
      </div>
      <div className="card-gold" style={{padding:'12px 16px',marginBottom:16,textAlign:'center'}}><div style={{fontFamily:'Amiri,serif',fontSize:16,color:'#f0d060'}}>بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ</div></div>
      {filtered.map(s=>(<div key={s.n} className="card" onClick={()=>loadSurah(s)} style={{marginBottom:8,padding:'14px 16px',cursor:'pointer',display:'flex',alignItems:'center',gap:12}}><div style={{width:36,height:36,borderRadius:10,background:'rgba(201,162,39,0.12)',border:'1px solid rgba(201,162,39,0.2)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:12,fontWeight:800,color:'#c9a227',flexShrink:0}}>{s.n}</div><div style={{flex:1}}><div style={{fontWeight:700,color:'#fff',fontSize:14}}>{lang==='bn'?s.bnName:s.name}</div><div style={{fontSize:11,color:'#5a6a7a',marginTop:1}}>{lang==='bn'?s.bnMeaning:s.meaning} · {s.v} {t('quran.verses')}</div></div><div style={{fontFamily:'Amiri,serif',fontSize:18,color:'#c9a227'}}>{s.arabic}</div></div>))}
      <div style={{textAlign:'center',padding:16,fontSize:12,color:'#4a5a6a'}}>{t('quran.tap')}</div>
    </div>)}
    {showBk&&(<div>
      <button onClick={()=>setShowBk(false)} style={{background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.1)',color:'#aaa',borderRadius:10,padding:'8px 14px',cursor:'pointer',marginBottom:16,fontSize:13}}>{t('quran.surah.back')}</button>
      <div style={{fontSize:14,fontWeight:700,color:'#c9a227',marginBottom:12}}>🔖 {t('quran.bookmarks')} ({bk.length})</div>
      {bk.length===0?(<div className="card" style={{padding:'30px',textAlign:'center',color:'#5a6a7a',fontSize:13}}>{t('quran.no.bk')}</div>):bk.map(b=>(<div key={b.key} className="ayah-card" style={{marginBottom:10}}><div style={{fontSize:11,color:'#c9a227',fontWeight:600,marginBottom:6}}>{b.surah} · {t('quran.verse')} {b.ayah}</div><div style={{fontFamily:'Amiri,serif',fontSize:20,color:'#f0d060',textAlign:'right',lineHeight:1.8}}>{b.arabic}</div><div style={{fontSize:12,color:'#7a8a9a',marginTop:8,lineHeight:1.6}}>{b.tr}</div></div>))}
    </div>)}
    {sel&&(<div>
      <button onClick={()=>{setSel(null);setAyahs([])}} style={{background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.1)',color:'#aaa',borderRadius:10,padding:'8px 14px',cursor:'pointer',marginBottom:16,fontSize:13}}>{t('quran.surah.back')}</button>
      <div className="card-gold" style={{padding:'16px',marginBottom:16,textAlign:'center'}}><div style={{fontFamily:'Amiri,serif',fontSize:26,color:'#f0d060'}}>{sel.arabic}</div><div style={{fontSize:16,fontWeight:700,color:'#fff',marginTop:4}}>{lang==='bn'?sel.bnName:sel.name}</div><div style={{fontSize:12,color:'#8a9aaa'}}>{lang==='bn'?sel.bnMeaning:sel.meaning} · {sel.v} {t('quran.verses')}</div>{sel.n!==9&&<div style={{fontFamily:'Amiri,serif',fontSize:14,color:'#c9a227',marginTop:8}}>بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ</div>}</div>
      {loading&&Array(4).fill(0).map((_,i)=>(<div key={i} className="ayah-card" style={{marginBottom:10}}><div className="skeleton" style={{height:60,marginBottom:8}}/><div className="skeleton" style={{height:16,width:'80%'}}/></div>))}
      {err&&<div style={{color:'#e07070',textAlign:'center',padding:20,fontSize:13}}>{err}</div>}
      {ayahs.map(a=>{const k=sel.n+':'+a.numberInSurah;const bked=bk.find(b=>b.key===k);return(<div key={a.numberInSurah} className="ayah-card" style={{marginBottom:10}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:10}}><div style={{width:30,height:30,borderRadius:'50%',background:'linear-gradient(135deg,#c9a227,#a07d1a)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:11,fontWeight:800,color:'#040d1a'}}>{a.numberInSurah}</div><button onClick={()=>toggleBk(a)} style={{background:'none',border:'none',cursor:'pointer',fontSize:16,opacity:bked?1:0.4}}>🔖</button></div><div style={{fontFamily:'Amiri,serif',fontSize:22,color:'#f0d060',textAlign:'right',lineHeight:2,marginBottom:12}}>{a.text}</div><div style={{fontSize:13,color:'#7a8a9a',lineHeight:1.7,borderTop:'1px solid rgba(255,255,255,0.05)',paddingTop:10}}>{a.tr}</div></div>);})}
    </div>)}
    <div style={{height:20}}/>
  </div>);
}